import type { ChatMessage } from "@/lib/backend";

function lines(prefix: string, n: number, seed: string) {
    return Array.from({ length: n }, (_, i) => `    ${prefix}${String(i).padStart(2, "0")} ${seed}`).join("\n");
}

/** Dense Shape session as if you shipped a YouTube watch-page density overhaul. */
export function buildDemoChatMessages(): ChatMessage[] {
    const now = Date.now() / 1000;
    let t = now - 2400;

    const next = (dt = 45) => {
        t += dt;
        return t;
    };

    const playerOriginal = [
        "export function layoutWatchPage(ctx: WatchLayoutCtx) {",
        "  const theater = ctx.player.theater;",
        "  const comments = measureComments(ctx.comments, { density: \"comfortable\" });",
        "  return {",
        "    playerHeight: theater ? ctx.viewport.height * 0.72 : 360,",
        "    secondary: comments.height + 180,",
        "  };",
        "}",
        lines("oldLayout", 28, "comfortable column; shorts shelf ignored"),
    ].join("\n");

    const playerReplacement = [
        "export function layoutWatchPage(ctx: WatchLayoutCtx) {",
        "  const density = ctx.experiments.watchDensityV3 ? \"compact\" : \"comfortable\";",
        "  const theater = ctx.player.theater;",
        "  const comments = measureComments(ctx.comments, { density, liveChat: ctx.live });",
        "  const shorts = measureShortsShelf(ctx.shorts, { steal: !theater });",
        "  const thanks = measureSuperThanksRail(ctx.superThanks);",
        "  const ads = scheduleMidroll(ctx.ads, { avoid: [shorts.top, thanks.height] });",
        "  return {",
        "    playerHeight: theater ? ctx.viewport.height * 0.78 : density === \"compact\" ? 420 : 360,",
        "    secondary: comments.height + shorts.height + thanks.height,",
        "    adPod: ads,",
        "  };",
        "}",
        lines("newLayout", 28, "compact two-col; shorts + thanks + midroll"),
    ].join("\n");

    return [
        {
            role: "user",
            content: [
                "We're treating this like the YouTube watch page the week of an all-hands. Ship a **density** overhaul on `/watch` without breaking theater, live chat, or ads.",
                "",
                "Need in one pass:",
                "1. Player + secondary column share one measure pass (today comments reflow after the player commits, so the expander jumps).",
                "2. Compact two-column: metadata, Super Thanks chip rail, comments, Shorts shelf. Shorts cannot steal height from the player in theater.",
                "3. Midroll scheduler must not collide with Super Thanks or the live chat attach.",
                "4. Keep the existing `/watch?v=` URL and the engagement panel experiment.",
                "",
                "This is the big one — explore first, then spawn agents for player / comments / ads so we can move in parallel.",
            ].join("\n"),
            timestamp: next(0),
        },
        {
            role: "assistant",
            content: [
                "<rename_chat>Watch page density</rename_chat>",
                "<think>",
                "This is a layout + ads + comments coupling problem, not a visual restyle. WatchPlayer still measures comments after paint. Super Thanks is a chip rail above comments. Shorts shelf on the secondary column steals height in theater. Midroll uses the same vertical budget. I'll map the measure graph, then spawn three agents so player / comments / ads don't serialize.",
                "</think>",
                "<status>Mapping watch-page measure graph</status>",
                "<ls>youtube/watch</ls>",
                "<ls>youtube/player</ls>",
                "<search>layoutWatchPage measureComments</search>",
                "<search_result>youtube/watch/player/WatchPlayer.ts</search_result>",
                "<grep>scheduleMidroll</grep>",
                "<cat start=\"301\" end=\"561\">youtube/watch/player/WatchPlayer.ts</cat>",
                "<cat start=\"1\" end=\"220\">youtube/comments/CommentThread.tsx</cat>",
                "<cat start=\"40\" end=\"190\">youtube/ads/MidrollScheduler.ts</cat>",
                "<cat start=\"12\" end=\"88\">youtube/super_thanks/ChipRail.tsx</cat>",
                "<cat start=\"1\" end=\"140\">youtube/shorts/ShortsShelf.ts</cat>",
                "<web_search query=\"watch page two column density live chat\">",
                "### Watch page column spec",
                "URL: https://blog.youtube/inside-youtube/watch-page",
                "Secondary column is metadata, engagement, comments. Player owns theater height.",
                "---",
                "### Material density",
                "URL: https://m3.material.io/styles/density",
                "Compact density tightens vertical rhythm without changing hit targets.",
                "</web_search>",
                "<web_visit url=\"https://www.youtube.com/watch?v=jfKfPfyJRdk\" host=\"youtube.com\" title=\"Watch\" />",
                "<tool_call>",
                "[MCP youtube_internal__get_experiment] watch_page_density_v3",
                "</tool_call>",
                "<git_operation op=\"status\">",
                "[unstaged] M youtube/watch/player/WatchPlayer.ts",
                "[unstaged] M youtube/comments/CommentThread.tsx",
                "[unstaged] M youtube/ads/MidrollScheduler.ts",
                "</git_operation>",
                "<plan title=\"Watch page density\">",
                "<step status=\"done\">Map player, comments, shorts, thanks, midroll</step>",
                "<step status=\"active\">Spawn parallel agents</step>",
                "<step status=\"pending\">One measure pass + compact column</step>",
                "<step status=\"pending\">Midroll avoids thanks + live chat</step>",
                "</plan>",
                "<todos title=\"Watch page density\">",
                "<todo id=\"1\" status=\"done\">Find measure graph</todo>",
                "<todo id=\"2\" status=\"active\">Spawn player / comments / ads agents</todo>",
                "<todo id=\"3\" status=\"pending\">Patch layoutWatchPage</todo>",
                "<todo id=\"4\" status=\"pending\">Tests + lint + #watch-player note</todo>",
                "</todos>",
                "<subagent_ref id=\"demo-sub-player\" agent=\"Watch-page player\" model=\"auto\" task=\"Single measure pass for theater + compact two-col without clipping controls\" status=\"running\" />",
                "<subagent_ref id=\"demo-sub-comments\" agent=\"Comments density\" model=\"anthropic/claude-sonnet-4\" task=\"Comments + live chat share one measure; expander must not jump\" status=\"running\" />",
                "<subagent_ref id=\"demo-sub-ads\" agent=\"Midroll scheduler\" model=\"openai/gpt-5\" task=\"Midroll must not collide with Super Thanks chip or Shorts shelf\" status=\"running\" />",
                "",
                "Measure graph is split across five packages. Cards on the right are the three agents — player, comments, ads — not full chats. I'll keep going on the shared layout types while they run.",
            ].join("\n"),
            timestamp: next(95),
            model: "auto",
            stats: {
                timeMs: 48000,
                tokens: 12400,
                inputTokens: 9100,
                outputTokens: 3300,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Code",
            },
        },
        {
            role: "user",
            content: "Yes. Keep `/watch?v=` and the engagement panel. Super Thanks chip stays above comments even when live chat attaches. Don't let Shorts steal theater height.",
            timestamp: next(22),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "Constraints are locked: same URL, engagement panel stays, Super Thanks above comments, shorts never steal theater. I'll land layoutWatchPage, CommentThread measure, MidrollScheduler avoid-rects, and a compact ChipRail. Tests first on the measure helper, then the page.",
                "</think>",
                "<status>Landing compact two-column</status>",
                "<mkdir>youtube/watch/layout</mkdir>",
                "<create_file>youtube/watch/layout/density.ts</create_file>",
                "<edit file=\"youtube/watch/layout/density.ts\">",
                "<original>",
                "",
                "</original>",
                "<replacement>",
                "export type WatchDensity = \"comfortable\" | \"compact\";",
                "",
                "export function secondaryBudget(args: {",
                "  comments: number;",
                "  shorts: number;",
                "  thanks: number;",
                "  theater: boolean;",
                "}) {",
                "  const shorts = args.theater ? 0 : args.shorts;",
                "  return args.comments + shorts + args.thanks;",
                "}",
                "</replacement>",
                "</edit>",
                "<edit file=\"youtube/watch/player/WatchPlayer.ts\">",
                `<original>`,
                playerOriginal,
                `</original>`,
                `<replacement>`,
                playerReplacement,
                `</replacement>`,
                "</edit>",
                "<edit file=\"youtube/comments/CommentThread.tsx\">",
                "<original>",
                "measureComments(node, { density: \"comfortable\" });",
                "</original>",
                "<replacement>",
                "measureComments(node, { density, liveChat: live });",
                "</replacement>",
                "</edit>",
                "<edit file=\"youtube/super_thanks/ChipRail.tsx\">",
                "<original>",
                "gap: 12",
                "</original>",
                "<replacement>",
                "gap: density === \"compact\" ? 8 : 12",
                "</replacement>",
                "</edit>",
                "<edit file=\"youtube/shorts/ShortsShelf.ts\">",
                "<original>",
                "height: shelf.natural",
                "</original>",
                "<replacement>",
                "height: theater ? 0 : shelf.natural",
                "</replacement>",
                "</edit>",
                "<edit file=\"youtube/ads/MidrollScheduler.ts\">",
                "<original>",
                "return nextPod(playerTime);",
                "</original>",
                "<replacement>",
                "return nextPod(playerTime, { avoid: [thanks.top, shorts.top, liveChat.top] });",
                "</replacement>",
                "</edit>",
                "<edit_pending id=\"demo-edit-exp\" file=\"youtube/watch/experiments.ts\" status=\"applied\">",
                "<original>",
                "watch_page_density_v3: false,",
                "</original>",
                "<replacement>",
                "watch_page_density_v3: true,",
                "</replacement>",
                "</edit_pending>",
                "<edit_pending id=\"demo-edit-e2e\" file=\"youtube/watch/watch.spec.ts\" status=\"pending\">",
                "<original>",
                "test(\"theater keeps player height\", () => {});",
                "</original>",
                "<replacement>",
                "test(\"theater keeps player height\", async () => {",
                "  expect(layout.shorts).toBe(0);",
                "  expect(layout.thanks).toBeGreaterThan(0);",
                "});",
                "</replacement>",
                "</edit_pending>",
                "<terminal_command id=\"demo-term-unit\" status=\"completed\" exit=\"0\">",
                "npm test -- youtube/watch/layout/density.test.ts",
                "",
                "✓ secondaryBudget zeros shorts in theater",
                "✓ Super Thanks still counts when live chat attaches",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-lint\" status=\"completed\" exit=\"0\">",
                "npx eslint youtube/watch youtube/comments youtube/ads --max-warnings=0",
                "",
                "✓ no linter errors",
                "</terminal_command>",
                "<git_operation op=\"diff\">",
                "[file] youtube/watch/player/WatchPlayer.ts",
                "@@ layoutWatchPage",
                "-  secondary: comments.height + 180,",
                "+  secondary: comments.height + shorts.height + thanks.height,",
                "+  adPod: ads,",
                "</git_operation>",
                "<git_operation op=\"log\">",
                "[commit] b7e12c4|2026-09-14|mprakash|watch: split comments measure after player paint",
                "[commit] 91aa02d|2026-09-12|slee|ads: midroll uses playerTime only",
                "</git_operation>",
                "<plugin_call toolkit=\"slack\" slug=\"SLACK_SEND_MESSAGE\" label=\"Send message\" status=\"ok\">",
                "Posted to #watch-player: density v3 on one measure pass. Theater keeps player; Shorts shelf is secondary-only.",
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"rejected\">",
                "Rejected",
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"pending\" id=\"demo-plugin-linear\">",
                "Awaiting approval",
                "</plugin_call>",
                "<terminal_command id=\"demo-term-e2e\" status=\"pending\">",
                "npx playwright test youtube/watch/watch.spec.ts --project=chromium",
                "",
                "Awaiting approval: plays a watch page against local player + ads stub",
                "</terminal_command>",
                "",
                "Player, comments, Shorts, Super Thanks, and midroll now share the same budget. Theater zeros the shelf. Chip rail stays above comments when live chat attaches.",
                "",
                "Approve the e2e and the Linear retry if you still want WATCH-4402 for leftover live-chat tests.",
            ].join("\n"),
            timestamp: next(180),
            model: "auto",
            stats: {
                timeMs: 91000,
                tokens: 28600,
                inputTokens: 19200,
                outputTokens: 9400,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Code",
            },
        },
        {
            role: "user",
            content: "Paste the review as markdown — headings, a table, the patch — and keep the player diff open. It looked truncated.",
            timestamp: next(18),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "They want a skim-able review plus the big player diff. The WatchPlayer replacement is over the preview limit; show the truncated diff honestly and summarize the rest in markdown. Adversarial review on ads vs thanks.",
                "</think>",
                "<status>Reviewing changes</status>",
                "<cat start=\"301\" end=\"2561\">youtube/watch/player/WatchPlayer.ts</cat>",
                "<cat start=\"1\" end=\"420\">youtube/comments/CommentThread.tsx</cat>",
                "<edit file=\"youtube/watch/player/WatchPlayer.ts\">",
                `<original>`,
                playerOriginal,
                `</original>`,
                `<replacement>`,
                playerReplacement,
                `</replacement>`,
                "</edit>",
                "<review_debate model=\"anthropic/claude-sonnet-4\">",
                JSON.stringify({
                    verdict: {
                        confirmed_issues: [
                            "WatchPlayer previously measured comments after paint, so the expander jumped.",
                            "Shorts shelf could steal theater height.",
                            "Midroll used playerTime only and ignored Super Thanks + live chat rects.",
                        ],
                        disputed_points: [
                            "Engagement panel experiment still owns the right rail on web; density v3 must not hide it.",
                        ],
                        confidence: "high",
                        minimal_fix_plan: [
                            "Keep one measure pass in layoutWatchPage.",
                            "Zero Shorts height in theater.",
                            "Pass avoid-rects into scheduleMidroll.",
                        ],
                        tipping_evidence: [
                            "density.test.ts: secondaryBudget zeros shorts in theater.",
                            "ChipRail still contributes height when live chat attaches.",
                        ],
                    },
                }),
                "</review_debate>",
                "<plan_saved path=\"docs/watch-density.md\" title=\"Watch page density\">",
                "## Ship notes",
                "",
                "- One measure pass",
                "- Theater keeps player height",
                "- Super Thanks above comments",
                "</plan_saved>",
                "<git_operation op=\"stage\">",
                "Staged youtube/watch/player/WatchPlayer.ts",
                "</git_operation>",
                "<git_operation op=\"commit\">",
                "watch: compact density, shared measure, midroll avoid-rects",
                "</git_operation>",
                "",
                "## Watch page density",
                "",
                "This is the all-hands watch-page pass: **one measure graph** for player, comments, Super Thanks, Shorts, and midroll. `/watch?v=` is unchanged. The engagement panel experiment stays on.",
                "",
                "### What landed",
                "",
                "1. `layoutWatchPage` commits player + secondary together",
                "2. Compact density on comments + chip rail",
                "3. Shorts shelf height is `0` in theater",
                "4. Midroll `avoid` includes thanks, shorts, and live chat",
                "",
                "| Surface | Change | Status |",
                "| --- | --- | --- |",
                "| `WatchPlayer.ts` | shared measure + compact two-col | done |",
                "| `CommentThread.tsx` | density + live chat in one pass | done |",
                "| `ChipRail.tsx` | compact gap, stays above comments | done |",
                "| `ShortsShelf.ts` | no theater steal | done |",
                "| `MidrollScheduler.ts` | avoid-rects | done |",
                "| `watch.spec.ts` | theater + thanks assertions | pending approval |",
                "",
                "> Redirects, URLs, and the engagement panel are untouched. The expander just cannot jump.",
                "",
                "```ts",
                "const shorts = theater ? 0 : shelf.natural;",
                "const ads = scheduleMidroll(ctx.ads, { avoid: [shorts.top, thanks.height] });",
                "```",
                "",
                "Follow-up: [WATCH-4402](https://linear.app) after you approve the e2e and Linear create.",
                "",
                "The player diff in the workflow above is truncated — the preview limit cuts the layout helper. The full file is `youtube/watch/player/WatchPlayer.ts`.",
            ].join("\n"),
            timestamp: next(54),
            model: "auto",
            stats: {
                timeMs: 22000,
                tokens: 84000,
                inputTokens: 72000,
                outputTokens: 12000,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Review",
            },
        },
        {
            role: "user",
            content: "Delete the old comfortable-only helper if it's unused, and rename the stub we don't need.",
            timestamp: next(12),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "Cleanup only. Remove the unused comfortable helper and rename the leftover stub so the package graph matches density v3.",
                "</think>",
                "<delete_file>youtube/watch/layout/comfortable.ts</delete_file>",
                "<rename_file>youtube/watch/layout/legacy_shelf.ts → youtube/watch/layout/shorts_budget.ts</rename_file>",
                "",
                "Removed the comfortable-only helper. Shelf budget lives in `shorts_budget.ts`. Agents on the right should already be finishing — player, comments, ads.",
            ].join("\n"),
            timestamp: next(16),
            model: "auto",
            stats: {
                timeMs: 6400,
                tokens: 1800,
                inputTokens: 1100,
                outputTokens: 700,
                usedAuto: true,
                reasoningEffort: "low",
                mode: "Code",
            },
        },
    ];
}
