import type { ChatMessage } from "@/lib/backend";

function htmlPreview(buttonStyle: string, label = "Apply throttle") {
    const html = `<!doctype html><html><body style="margin:0;background:#16191f;display:grid;place-items:center;min-height:100vh;font-family:system-ui,sans-serif"><div id="root" style="display:flex;gap:12px"><button style="${buttonStyle}">${label}</button></div></body></html>`;
    return `data:text/html;charset=utf-8,${encodeURIComponent(html)}`;
}

function svgUrl(markup: string) {
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(markup)}`;
}

const CONSOLE_SHOT = svgUrl(
    `<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540">
  <rect width="960" height="540" fill="#16191f"/>
  <rect width="200" height="540" fill="#232f3e"/>
  <text x="24" y="40" fill="#fff" font-family="sans-serif" font-size="14">AWS Console</text>
  <text x="24" y="72" fill="#ff9900" font-family="sans-serif" font-size="12">API Gateway</text>
  <rect x="224" y="24" width="712" height="48" rx="6" fill="#232f3e"/>
  <text x="240" y="54" fill="#eaeded" font-family="sans-serif" font-size="18">Throttle policy · prod</text>
  <rect x="224" y="92" width="712" height="64" rx="8" fill="#3f2723"/>
  <text x="244" y="130" fill="#ffad97" font-family="sans-serif" font-size="14">Rate exceeded on ExecuteAPI. /prod still serving 429s after burst bump.</text>
  <rect x="224" y="180" width="340" height="120" rx="8" fill="#232f3e"/>
  <text x="244" y="216" fill="#d1d5db" font-family="sans-serif" font-size="12">Rate  10000 rps</text>
  <text x="244" y="244" fill="#d1d5db" font-family="sans-serif" font-size="12">Burst  5000</text>
  <rect x="580" y="220" width="140" height="36" rx="6" fill="#ff9900"/>
  <text x="598" y="243" fill="#16191f" font-family="sans-serif" font-size="13" font-weight="700">Apply throttle</text>
</svg>`,
);

const APIGW_ICON = svgUrl(
    `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">
  <rect width="96" height="96" rx="16" fill="#232f3e"/>
  <path fill="#ff9900" d="M48 18l28 16v28L48 78 20 62V34z"/>
  <path fill="#ec7211" d="M48 18l28 16-28 16L20 34z"/>
</svg>`,
);

const PREVIEW_GHOST = htmlPreview(
    "background:transparent;color:#d1d5db;border:1px solid #545b64;border-radius:8px;padding:8px 16px;font-size:14px",
);
const PREVIEW_SOLID = htmlPreview(
    "background:#ff9900;color:#16191f;border:none;border-radius:8px;padding:8px 16px;font-size:14px;font-weight:600",
);
const PREVIEW_SOFT = htmlPreview(
    "background:#232f3e;color:#ff9900;border:1px solid #ff9900;border-radius:8px;padding:8px 16px;font-size:14px",
);

const THROTTLE_BEFORE = [
    "export function applyUsagePlan(plan: UsagePlan): ExecuteApiPolicy {",
    "  return {",
    "    rateLimit: plan.rate ?? 10_000,",
    "    burstLimit: plan.burst ?? 5_000,",
    "    quota: plan.quota,",
    "  };",
    "}",
].join("\n");

const THROTTLE_AFTER = [
    "export function applyUsagePlan(plan: UsagePlan, ctx: StageCtx): ExecuteApiPolicy {",
    "  const density = ctx.console.compact ? \"compact\" : \"comfortable\";",
    "  const rate = clampRate(plan.rate ?? 10_000, ctx.account);",
    "  const burst = ctx.experiments.burstV2 ? Math.max(plan.burst ?? 5_000, rate) : (plan.burst ?? 5_000);",
    "  return {",
    "    rateLimit: rate,",
    "    burstLimit: burst,",
    "    quota: plan.quota,",
    "    alarm: cloudWatchAlarm(ctx.stage, { rate, burst }),",
    "    density,",
    "  };",
    "}",
].join("\n");

/** Dense Shape session: Amazon SDE shipping API Gateway throttle policy on the AWS console. */
export function buildDemoChatMessages(): ChatMessage[] {
    const now = Date.now() / 1000;
    let t = now - 2400;

    const next = (dt = 45) => {
        t += dt;
        return t;
    };

    return [
        {
            role: "user",
            content: [
                "/review this like SIM: prod API Gateway usage plans are 429-ing after we bumped burst. Keep `/prod` and the existing ExecuteAPI stage.",
                "",
                "Need in one pass:",
                "1. `applyUsagePlan` must share one write with CloudWatch alarms (today the banner commits, then the alarm patches, so Apply jumps).",
                "2. Compact console: rate, burst, quota, alarm chip. Burst cannot steal height from the stage picker in theater (wide) layout.",
                "3. Mid-window scheduler in the console preview must not collide with the alarm chip or live CloudWatch attach.",
                "4. Keep `execute-api.us-east-1.amazonaws.com` and the usage-plan experiment.",
                "",
                "@codebase @services/apigw @ThrottlePolicy.ts @design:radius-md",
                "",
                "CloudWatch dump + the console as it looks on my desk. Explore first, then spawn agents for policy / console / alarms.",
                "",
                `<attached_image name="apigw-console-prod.png" type="image/svg+xml">${CONSOLE_SHOT}</attached_image>`,
                `<attached_file name="apigw-throttling.log" type="text/plain" size="4821">`,
                "[ERROR] Rate exceeded: arn:aws:execute-api:us-east-1:226304153867:abc123/prod/POST/orders",
                "ThrottlingException  Too Many Requests  burst=5000 rate=10000",
                "x-amzn-RequestId  3f9c…  x-amzn-ErrorType  LimitExceededException",
                `</attached_file>`,
            ].join("\n"),
            timestamp: next(0),
        },
        {
            role: "assistant",
            content: [
                "<rename_chat>API Gateway throttle</rename_chat>",
                "<think>",
                "This is policy + console + alarms coupling, not a restyle. applyUsagePlan writes the banner first; CloudWatchAlarm patches after paint so Apply jumps. Burst chip on the secondary column steals height in wide layout. I'll map the write graph, then spawn three agents so policy / console / alarms don't serialize.",
                "</think>",
                "<thought>",
                "SIM ticket is APIGW-4402. Do not retarget `/prod`. Usage-plan experiment stays on.",
                "</thought>",
                "<status>Mapping ExecuteAPI write graph</status>",
                "<ls>services/apigw</ls>",
                "<ls>services/apigw-console</ls>",
                "<search>applyUsagePlan CloudWatchAlarm</search>",
                "<search_result query=\"applyUsagePlan CloudWatchAlarm\">",
                "services/apigw/ThrottlePolicy.ts:88-140 (score 0.94)",
                "export function applyUsagePlan(plan: UsagePlan): ExecuteApiPolicy",
                "---",
                "services/apigw-console/AlarmChip.tsx:12-88 (score 0.81)",
                "CloudWatchAlarm patches after banner commit",
                "</search_result>",
                "<grep>scheduleMidWindow</grep>",
                "<cat start=\"88\" end=\"180\">services/apigw/ThrottlePolicy.ts</cat>",
                "<cat start=\"1\" end=\"160\">services/apigw-console/ThrottleApply.tsx</cat>",
                "<cat start=\"40\" end=\"190\">services/apigw/CloudWatchAlarm.ts</cat>",
                "<web_search query=\"API Gateway usage plan rate burst quota ExecuteAPI 429\">",
                "### Usage plans and throttling",
                "URL: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
                "Rate is steady-state RPS. Burst is token bucket. Stage `/prod` inherits the usage plan unless overridden.",
                "---",
                "### CloudWatch ExecuteAPI metrics",
                "URL: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html",
                "4XXError and Count on ApiName, Stage. Alarm should share the same write as the banner.",
                "</web_search>",
                "<web_result query=\"API Gateway usage plan rate burst quota ExecuteAPI 429\">",
                "### Usage plans and throttling",
                "URL: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html",
                "Rate is steady-state RPS. Burst is token bucket. Stage `/prod` inherits the usage plan unless overridden.",
                "---",
                "### CloudWatch ExecuteAPI metrics",
                "URL: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html",
                "4XXError and Count on ApiName, Stage.",
                "</web_result>",
                `<web_visit url="https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/abc123/stages/prod" host="console.aws.amazon.com" title="API Gateway · prod" />`,
                "<tool_call>",
                "[MCP aws-api-gateway__get_usage_plan] prod-orders-plan",
                "</tool_call>",
                "<tool_result>",
                "[MCP aws-api-gateway__get_usage_plan]",
                "id: prod-orders-plan",
                "throttle.rateLimit: 10000",
                "throttle.burstLimit: 5000",
                "quota.limit: 1e7 / DAY",
                "stageKeys: abc123/prod",
                "</tool_result>",
                "<tool_call>",
                "[MCP aws-cloudwatch__describe_alarms] ExecuteAPI-4XX-prod",
                "</tool_call>",
                "<tool_result>",
                "[MCP aws-cloudwatch__describe_alarms]",
                "AlarmName ExecuteAPI-4XX-prod  State ALARM  Metric 4XXError  Period 60",
                "Last write lagged banner commit by ~180ms — matches the Apply jump.",
                "</tool_result>",
                "<git_operation op=\"status\">",
                "[unstaged] M services/apigw/ThrottlePolicy.ts",
                "[unstaged] M services/apigw-console/ThrottleApply.tsx",
                "[unstaged] M services/apigw/CloudWatchAlarm.ts",
                "</git_operation>",
                "<git_operation op=\"branches\">",
                "[*] sim/apigw-throttle-v2",
                "[ ] mainline",
                "[r] origin/sim/apigw-throttle-v2",
                "</git_operation>",
                "<git_operation op=\"log\">",
                "[commit] b7e12c4|2026-09-14|mprakash|apigw: split alarm write after banner paint",
                "[commit] 91aa02d|2026-09-12|slee|console: burst chip uses leftover secondary height",
                "</git_operation>",
                "<git_operation op=\"fetch\">",
                "origin/sim/apigw-throttle-v2 up to date",
                "</git_operation>",
                "<plan title=\"API Gateway throttle\">",
                "<step status=\"done\">Map policy, console, alarms, usage plan</step>",
                "<step status=\"active\">Spawn parallel agents</step>",
                "<step status=\"pending\">One write pass + compact Apply</step>",
                "<step status=\"pending\">Alarm chip shares banner commit</step>",
                "</plan>",
                "<todos title=\"API Gateway throttle\">",
                "<todo id=\"1\" status=\"done\">Find write graph</todo>",
                "<todo id=\"2\" status=\"active\">Spawn policy / console / alarm agents</todo>",
                "<todo id=\"3\" status=\"pending\">Patch applyUsagePlan</todo>",
                "<todo id=\"4\" status=\"pending\">Tests + lint + #apigw-console note</todo>",
                "</todos>",
                "<subagent_ref id=\"demo-sub-policy\" agent=\"Usage-plan policy\" model=\"auto\" task=\"Single write for rate + burst + quota without clipping the stage picker\" status=\"running\" />",
                "<subagent_ref id=\"demo-sub-console\" agent=\"Console Apply\" model=\"anthropic/claude-sonnet-4\" task=\"Apply + alarm chip share one measure; banner must not jump\" status=\"running\" />",
                "<subagent_ref id=\"demo-sub-alarms\" agent=\"CloudWatch alarms\" model=\"openai/gpt-5\" task=\"Alarm write must not collide with burst chip or live CW attach\" status=\"running\" />",
                `<questions id="ask-demo" status="pending">`,
                JSON.stringify({
                    questions: [
                        {
                            id: "weight",
                            prompt: "Which Apply throttle weight should land in the console?",
                            options: [
                                { id: "ghost", label: "Ghost" },
                                { id: "solid", label: "Solid", recommended: true },
                                { id: "soft", label: "Soft" },
                            ],
                        },
                        {
                            id: "burst",
                            prompt: "When burst is below rate on an existing plan, what should we do?",
                            options: [
                                { id: "clamp", label: "Raise burst to rate", recommended: true },
                                { id: "keep", label: "Keep the stored burst" },
                            ],
                        },
                    ],
                    answers: null,
                }),
                `</questions>`,
                "",
                "Write graph is split across `ThrottlePolicy`, `ThrottleApply`, and `CloudWatchAlarm`. Cards on the right are the three agents — policy, console, alarms — not full chats. MCP says prod-orders-plan is still 10k/5k; the alarm lags the banner by ~180ms, which is the jump in your screenshot.",
                "",
                "Pick the Apply weight and the burst clamp before I show styles. `/prod` and ExecuteAPI stay put.",
            ].join("\n"),
            timestamp: next(95),
            model: "auto",
            stats: {
                timeMs: 48000,
                tokens: 12400,
                inputTokens: 9100,
                outputTokens: 3300,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Plan",
            },
        },
        {
            role: "user",
            content: [
                "Solid, and raise burst to rate. Keep `/prod` and the usage-plan experiment. Alarm chip stays above quota even when live CloudWatch attaches. Don't let burst steal theater height.",
                "",
                "/test then a Visual pass on Apply — show me a few button styles before you add it. @ThrottleApply.tsx @design:radius-md",
            ].join("\n"),
            timestamp: next(22),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "They locked Solid + clamp burst up to rate. Show three styles of the same Apply control, generate the console mark, then screenshot localhost and inspect runtime before I write files.",
                "</think>",
                "<status>Creating preview</status>",
                `<questions id="ask-demo" status="answered">`,
                JSON.stringify({
                    questions: [
                        {
                            id: "weight",
                            prompt: "Which Apply throttle weight should land in the console?",
                            options: [
                                { id: "ghost", label: "Ghost" },
                                { id: "solid", label: "Solid", recommended: true },
                                { id: "soft", label: "Soft" },
                            ],
                        },
                        {
                            id: "burst",
                            prompt: "When burst is below rate on an existing plan, what should we do?",
                            options: [
                                { id: "clamp", label: "Raise burst to rate", recommended: true },
                                { id: "keep", label: "Keep the stored burst" },
                            ],
                        },
                    ],
                    answers: { weight: "solid", burst: "clamp" },
                }),
                `</questions>`,
                `<design_previews id="dp-demo" status="selected" selected="solid">`,
                `<design_preview id="ghost" name="Ghost" style="Quiet border" path="${PREVIEW_GHOST}" width="640" height="360" kind="html"/>`,
                `<design_preview id="solid" name="Solid" style="Filled accent" path="${PREVIEW_SOLID}" width="640" height="360" kind="html"/>`,
                `<design_preview id="soft" name="Soft" style="Tinted surface" path="${PREVIEW_SOFT}" width="640" height="360" kind="html"/>`,
                `</design_previews>`,
                `<generated_svg prompt="API Gateway orange cube mark for the throttle console" credits="0.40">${APIGW_ICON}</generated_svg>`,
                `<generated_image prompt="AWS console header strip, dark, API Gateway throttle" credits="0.80">${CONSOLE_SHOT}</generated_image>`,
                `<attached_image name="page.png" type="image/svg+xml">${CONSOLE_SHOT}</attached_image>`,
                "<inspect_runtime url=\"http://127.0.0.1:3000/apigateway/stages/prod\" kind=\"Chromium\">",
                "Console · 2 warnings · Apply jump 184ms after alarm patch · no Build Error",
                "</inspect_runtime>",
                "<plugin_call toolkit=\"pagerduty\" slug=\"PAGERDUTY_RESOLVE_INCIDENT\" label=\"Resolve incident\" status=\"ok\">",
                "Resolved SIM-1844 (ExecuteAPI 429 storm) as related; leaving APIGW-4402 open for the banner jump.",
                "</plugin_call>",
                "",
                "Solid is the one in the gallery. Same control, three styles; cube mark is for the console chrome if you want it saved later. Inspect on localhost still shows the 184ms jump — that's the alarm write, not the button.",
                "",
                "Say land it and I'll put Solid on @ThrottleApply.tsx with `@design:radius-md` and clamp burst in `applyUsagePlan`.",
            ].join("\n"),
            timestamp: next(40),
            model: "auto",
            stats: {
                timeMs: 22000,
                tokens: 8600,
                inputTokens: 5400,
                outputTokens: 3200,
                usedAuto: true,
                reasoningEffort: "medium",
                mode: "Visual",
            },
        },
        {
            role: "user",
            content: "Land Solid. Post #apigw-console when tests are green. Linear retry if the first create gets rejected.",
            timestamp: next(16),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "Constraints locked: Solid Apply, burst raised to rate, `/prod` stays, alarm chip above quota, burst never steals wide-layout height. Tests first on clampRate, then the page.",
                "</think>",
                "<status>Landing compact Apply</status>",
                "<mkdir>services/apigw/policy</mkdir>",
                "<create_file>services/apigw/policy/clamp.ts</create_file>",
                "<edit file=\"services/apigw/policy/clamp.ts\">",
                "<original>",
                "",
                "</original>",
                "<replacement>",
                "export function clampRate(rate: number, account: AccountCtx) {",
                "  return Math.min(rate, account.quotaRps);",
                "}",
                "",
                "export function secondaryBudget(args: { quota: number; burst: number; alarm: number; theater: boolean }) {",
                "  const burst = args.theater ? 0 : args.burst;",
                "  return args.quota + burst + args.alarm;",
                "}",
                "</replacement>",
                "</edit>",
                "<edit file=\"services/apigw/ThrottlePolicy.ts\">",
                `<original>`,
                THROTTLE_BEFORE,
                `</original>`,
                `<replacement>`,
                THROTTLE_AFTER,
                `</replacement>`,
                "</edit>",
                "<edit file=\"services/apigw-console/ThrottleApply.tsx\">",
                "<original>",
                "variant: \"ghost\"",
                "</original>",
                "<replacement>",
                "variant: \"solid\"",
                "</replacement>",
                "</edit>",
                "<edit file=\"services/apigw/CloudWatchAlarm.ts\">",
                "<original>",
                "return nextWindow(bannerTime);",
                "</original>",
                "<replacement>",
                "return nextWindow(bannerTime, { avoid: [thanks.top, burst.top, liveCw.top] });",
                "</replacement>",
                "</edit>",
                "<edit_pending id=\"demo-edit-exp\" file=\"services/apigw/experiments.ts\" status=\"applied\">",
                "<original>",
                "burst_v2: false,",
                "</original>",
                "<replacement>",
                "burst_v2: true,",
                "</replacement>",
                "</edit_pending>",
                "<edit_pending id=\"demo-edit-copy\" file=\"services/apigw-console/copy.ts\" status=\"rejected\">",
                "<original>",
                "Apply changes",
                "</original>",
                "<replacement>",
                "Ship throttle",
                "</replacement>",
                "</edit_pending>",
                "<edit_pending id=\"demo-edit-e2e\" file=\"services/apigw-console/throttle.spec.ts\" status=\"pending\">",
                "<original>",
                "test(\"wide layout keeps stage picker height\", () => {});",
                "</original>",
                "<replacement>",
                "test(\"wide layout keeps stage picker height\", async () => {",
                "  expect(layout.burst).toBe(0);",
                "  expect(layout.alarm).toBeGreaterThan(0);",
                "});",
                "</replacement>",
                "</edit_pending>",
                "<run>npm test -- services/apigw/policy/clamp.test.ts</run>",
                "<terminal_command id=\"demo-term-unit\" status=\"completed\" exit=\"0\">",
                "npm test -- services/apigw/policy/clamp.test.ts",
                "",
                "✓ clampRate respects account quota",
                "✓ secondaryBudget zeros burst in wide layout",
                "✓ alarm still counts when live CloudWatch attaches",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-lint\" status=\"completed\" exit=\"0\">",
                "npx eslint services/apigw services/apigw-console --max-warnings=0",
                "",
                "✓ no linter errors",
                "</terminal_command>",
                "<tool_result>",
                "[read_lints]",
                "services/apigw/ThrottlePolicy.ts: clean",
                "services/apigw-console/ThrottleApply.tsx: clean",
                "</tool_result>",
                "<terminal_command id=\"demo-term-integ\" status=\"error\" exit=\"1\">",
                "npm test -- services/apigw/integ/execute-api.spec.ts",
                "",
                "✗ usage plan still 5k burst on fixture from last week — rerunning against burst_v2 flag",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-integ-2\" status=\"completed\" exit=\"0\">",
                "BURST_V2=1 npm test -- services/apigw/integ/execute-api.spec.ts",
                "",
                "✓ burst raised to rate on existing plans",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-dev\" status=\"background\" session=\"3\">",
                "npm run dev -- --filter=apigw-console",
                "",
                "Local console on http://127.0.0.1:3000/apigateway/stages/prod",
                "</terminal_command>",
                "<tool_result>",
                "[list_terminals]",
                "3  background  npm run dev -- --filter=apigw-console",
                "4  idle",
                "</tool_result>",
                "<tool_result>",
                "[terminal_read]",
                "ready compiled /apigateway/stages/prod in 312ms",
                "</tool_result>",
                "<terminal_command id=\"demo-term-e2e\" status=\"pending\">",
                "npx playwright test services/apigw-console/throttle.spec.ts --project=chromium",
                "",
                "Awaiting approval: hits local ExecuteAPI stub + CloudWatch fixture",
                "</terminal_command>",
                "<git_operation op=\"diff\">",
                "[file] services/apigw/ThrottlePolicy.ts",
                "@@ applyUsagePlan",
                "-  burstLimit: plan.burst ?? 5_000,",
                "+  burstLimit: ctx.experiments.burstV2 ? Math.max(plan.burst ?? 5_000, rate) : (plan.burst ?? 5_000),",
                "+  alarm: cloudWatchAlarm(ctx.stage, { rate, burst }),",
                "</git_operation>",
                "<git_operation op=\"stage\">",
                "Staged services/apigw/ThrottlePolicy.ts",
                "</git_operation>",
                "<git_operation op=\"stage\">",
                "Staged services/apigw-console/ThrottleApply.tsx",
                "</git_operation>",
                "<git_operation op=\"stage\">",
                "Staged services/apigw/CloudWatchAlarm.ts",
                "</git_operation>",
                "<plugin_call toolkit=\"slack\" slug=\"SLACK_SEND_MESSAGE\" label=\"Send message\" status=\"ok\">",
                "Posted to #apigw-console: burst_v2 on one write pass. Wide layout keeps the stage picker; Solid Apply; alarm chip is secondary-only.",
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"rejected\">",
                "Rejected — SIM project required",
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"pending\" id=\"demo-plugin-linear\">",
                "Awaiting approval: APIGW-4402 leftover live-CW tests",
                "</plugin_call>",
                "<plugin_call toolkit=\"github\" slug=\"GITHUB_CREATE_PR_COMMENT\" label=\"Comment on PR\" status=\"ok\">",
                "Commented on amazon-archives/apigw-console#1844 with clampRate coverage.",
                "</plugin_call>",
                "<subagent_ref id=\"demo-sub-policy\" agent=\"Usage-plan policy\" model=\"auto\" task=\"Single write for rate + burst + quota without clipping the stage picker\" status=\"done\" />",
                "<subagent_ref id=\"demo-sub-console\" agent=\"Console Apply\" model=\"anthropic/claude-sonnet-4\" task=\"Apply + alarm chip share one measure; banner must not jump\" status=\"done\" />",
                "<subagent_ref id=\"demo-sub-alarms\" agent=\"CloudWatch alarms\" model=\"openai/gpt-5\" task=\"Alarm write must not collide with burst chip or live CW attach\" status=\"done\" />",
                "",
                "Policy, Apply, burst, and the alarm now share the same write. Wide layout zeros the burst chip. Solid Apply stays above quota when live CloudWatch attaches. Copy change was rejected — left “Apply changes”.",
                "",
                "Approve the e2e and the Linear retry if you still want APIGW-4402 for leftover live-CW tests.",
            ].join("\n"),
            timestamp: next(180),
            model: "auto",
            stats: {
                timeMs: 91000,
                tokens: 28600,
                inputTokens: 19200,
                outputTokens: 9400,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Code",
            },
        },
        {
            role: "user",
            content: "Paste the review as markdown — headings, a table, the patch — and keep the policy diff open. It looked truncated. Delete the old comfortable-only helper if it's unused.",
            timestamp: next(18),
        },
        {
            role: "assistant",
            content: [
                "<thought>",
                "They want a skim-able review plus the big policy diff. Show the truncated helper honestly. Adversarial pass on alarms vs burst.",
                "</thought>",
                "<status>Reviewing changes</status>",
                "<cat start=\"88\" end=\"420\">services/apigw/ThrottlePolicy.ts</cat>",
                "<edit file=\"services/apigw/ThrottlePolicy.ts\">",
                `<original>`,
                THROTTLE_BEFORE,
                `</original>`,
                `<replacement>`,
                THROTTLE_AFTER,
                `</replacement>`,
                "</edit>",
                "<delete_file>services/apigw/policy/comfortable.ts</delete_file>",
                "<rename_file>services/apigw/policy/legacy_burst.ts → services/apigw/policy/burst_budget.ts</rename_file>",
                "<review_debate model=\"anthropic/claude-sonnet-4\">",
                JSON.stringify({
                    verdict: {
                        confirmed_issues: [
                            "applyUsagePlan previously wrote the banner before the alarm, so Apply jumped.",
                            "Burst chip could steal wide-layout stage-picker height.",
                            "Mid-window used bannerTime only and ignored alarm + live CloudWatch rects.",
                        ],
                        disputed_points: [
                            "Usage-plan experiment still owns the right rail on web; burst_v2 must not hide it.",
                        ],
                        confidence: "high",
                        minimal_fix_plan: [
                            "Keep one write pass in applyUsagePlan.",
                            "Zero burst height in wide layout.",
                            "Pass avoid-rects into nextWindow.",
                        ],
                        tipping_evidence: [
                            "clamp.test.ts: secondaryBudget zeros burst in wide layout.",
                            "AlarmChip still contributes height when live CloudWatch attaches.",
                        ],
                    },
                }),
                "</review_debate>",
                "<plan_saved path=\"docs/apigw-throttle.md\" title=\"API Gateway throttle\">",
                "## Ship notes",
                "",
                "- One write pass",
                "- Wide layout keeps stage picker",
                "- Alarm chip above quota",
                "</plan_saved>",
                "<git_operation op=\"commit\">",
                "apigw: compact Apply, shared write, burst clamp, alarm avoid-rects",
                "</git_operation>",
                "<todos title=\"API Gateway throttle\">",
                "<todo id=\"1\" status=\"done\">Find write graph</todo>",
                "<todo id=\"2\" status=\"done\">Spawn policy / console / alarm agents</todo>",
                "<todo id=\"3\" status=\"done\">Patch applyUsagePlan</todo>",
                "<todo id=\"4\" status=\"done\">Tests + lint + #apigw-console note</todo>",
                "<todo id=\"5\" status=\"cancelled\">Comfortable-only helper</todo>",
                "</todos>",
                "<tool_result>",
                "[save_media]",
                "Wrote public/apigw-mark.svg from generated cube (only because they asked to keep the mark).",
                "</tool_result>",
                "",
                "## API Gateway throttle",
                "",
                "This is the SIM watch-page pass for ExecuteAPI: **one write graph** for policy, Apply, burst, quota, and CloudWatch. `/prod` is unchanged. The usage-plan experiment stays on.",
                "",
                "### What landed",
                "",
                "1. `applyUsagePlan` commits banner + alarm together",
                "2. Solid Apply on the console",
                "3. Burst height is `0` in wide layout",
                "4. Mid-window `avoid` includes alarm, burst, and live CloudWatch",
                "",
                "| Surface | Change | Status |",
                "| --- | --- | --- |",
                "| `ThrottlePolicy.ts` | shared write + burst clamp | done |",
                "| `ThrottleApply.tsx` | Solid variant | done |",
                "| `AlarmChip.tsx` | stays above quota | done |",
                "| `CloudWatchAlarm.ts` | avoid-rects | done |",
                "| `throttle.spec.ts` | wide layout + alarm assertions | pending approval |",
                "",
                "> Redirects, stage URLs, and the usage-plan experiment are untouched. Apply just cannot jump.",
                "",
                "```ts",
                "const burst = theater ? 0 : shelf.natural;",
                "const ads = nextWindow(ctx.ads, { avoid: [burst.top, alarm.height] });",
                "```",
                "",
                "Follow-up: [APIGW-4402](https://linear.app) after you approve the e2e and Linear create.",
                "",
                "The policy diff above is truncated at the preview limit. Full file is `services/apigw/ThrottlePolicy.ts`. Removed `comfortable.ts`; burst budget lives in `burst_budget.ts`.",
            ].join("\n"),
            timestamp: next(54),
            model: "auto",
            stats: {
                timeMs: 22000,
                tokens: 84000,
                inputTokens: 72000,
                outputTokens: 12000,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Review",
            },
        },
    ];
}
