import type { ChatMessage } from "@/lib/backend";

let demoChatPinned = false;

/** Keep the in-app demo on screen across hot reloads. */
export function setDemoChatPinned(pinned: boolean) {
    demoChatPinned = pinned;
}

export function isDemoChatPinned() {
    return demoChatPinned;
}

function svgUrl(markup: string) {
    return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(markup)}`;
}

const STORY_SHOT = svgUrl(
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360">
  <rect width="640" height="360" fill="#18191a"/>
  <rect x="24" y="24" width="592" height="64" rx="8" fill="#242526"/>
  <text x="44" y="62" fill="#e4e6eb" font-family="sans-serif" font-size="16">Feed story</text>
  <rect x="24" y="104" width="220" height="28" rx="6" fill="#3a3b3c"/>
  <text x="36" y="123" fill="#e4e6eb" font-family="sans-serif" font-size="12">See why</text>
</svg>`,
);

const CHIP_MARK = svgUrl(
    `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">
  <rect width="96" height="96" rx="20" fill="#3a3b3c"/>
  <path fill="#e4e6eb" d="M48 22l22 12v24L48 74 26 58V34z"/>
</svg>`,
);

const LABEL_BEFORE = [
    "function WarningLabel(props: { reason: string }) {",
    "  return <Chip label=\"See why\" reason={props.reason} />;",
    "}",
].join("\n");

const LABEL_AFTER = [
    "function WarningLabel(props: { reason: string }) {",
    "  return (",
    "    <Chip",
    "      label=\"See why\"",
    "      reason={props.reason}",
    "      reserveHeight",
    "    />",
    "  );",
    "}",
].join("\n");

/** Feed engineer, www checkout of the Facebook repo. Blocks show up when the work needs them. */
export function buildDemoChatMessages(): ChatMessage[] {
    const now = Date.now() / 1000;
    let t = now - 60 * 40;
    const next = (dt = 40) => {
        t += dt;
        return t;
    };

    return [
        {
            role: "user",
            content: [
                "Feed stories with a warning label jump about a frame after paint. The See why chip mounts late and shoves the body down. Ranking experiment stays on. Don't touch `feed/ranking`.",
                "",
                "Desk shot, the oncall log, a voice note, and the terminal from the repro.",
                "",
                `<attached_image name="feed-story-jump.png" type="image/svg+xml" size="2400">${STORY_SHOT}</attached_image>`,
                `<attached_file name="integrity-oncall.log" type="text/plain" size="860">`,
                "[feed] WarningLabel committed after story measure",
                "shift=18px story_id=9241881 surface=home",
                `</attached_file>`,
                `<attached_file name="Terminal.txt" type="text/x-shape-terminal" size="220">`,
                "$ js1 www/js/feed/integrity/WarningLabel-test.js",
                "FAIL  chip mounts after the story height is locked",
                `</attached_file>`,
                `<attached_file name="Voice note.webm" type="audio/webm" size="184320"></attached_file>`,
                `<attached_file name="WarningLabel.react.js" type="text/x-shape-code" size="180">`,
                "function WarningLabel(props) {",
                "  return <Chip label=\"See why\" reason={props.reason} />;",
                "}",
                `</attached_file>`,
            ].join("\n"),
            timestamp: next(0),
        },
        {
            role: "assistant",
            content: [
                "<rename_chat>Feed warning jump</rename_chat>",
                "<think>",
                "The story measures before WarningLabel exists, then the chip inserts and the body drops. I should find the measure call and the chip, and leave ranking alone.",
                "</think>",
                "<thought>",
                "Home surface only. The ranking experiment flag stays where it is.",
                "</thought>",
                "<status>Finding the measure</status>",
                "<ls>www/js/feed/integrity</ls>",
                "<ls>www/js/feed/story</ls>",
                "<search>WarningLabel story measure</search>",
                "<grep>reserveHeight</grep>",
                "<search_result query=\"WarningLabel story measure\">",
                "www/js/feed/integrity/WarningLabel.react.js:12-28 (score 0.91)",
                "function WarningLabel(props)",
                "---",
                "www/js/feed/story/FeedStory.react.js:140-166 (score 0.77)",
                "measureStory() runs before the chip commits",
                "</search_result>",
                "<cat start=\"140\" end=\"166\">www/js/feed/story/FeedStory.react.js</cat>",
                "The story locks its height, then `WarningLabel` commits and the body moves 18px. `reserveHeight` is not on the chip. I'll read the chip next and leave `feed/ranking` alone.",
            ].join("\n"),
            timestamp: next(50),
            model: "auto",
            stats: {
                timeMs: 14000,
                tokens: 5100,
                inputTokens: 3600,
                outputTokens: 1500,
                usedAuto: true,
                reasoningEffort: "medium",
                mode: "Code",
            },
        },
        {
            role: "user",
            content: "Check the Graph API feed docs before you change the chip. I want the public field names, not a guess.",
            timestamp: next(30),
        },
        {
            role: "assistant",
            content: [
                "<status>Checking the feed reference</status>",
                "<web_search>Graph API page feed story fields</web_search>",
                "<web_result query=\"Graph API page feed story fields\">",
                "developers.facebook.com — Page feed returns message, story, and attachments",
                "</web_result>",
                "<web_visit url=\"https://developers.facebook.com/docs/graph-api/reference/page/feed/\" host=\"developers.facebook.com\" title=\"Page Feed\" />",
                `<browse_session id="demo-feed-docs" status="stopped" url="https://developers.facebook.com/docs/graph-api/reference/page/feed/" title="Page Feed">${JSON.stringify({ image: STORY_SHOT, x: 42, y: 58 })}</browse_session>`,
                "<plan>",
                "1. Keep the ranking experiment untouched.",
                "2. Reserve the chip height before measureStory().",
                "3. Match the public fields: message, story, attachments. Do not invent a new story field.",
                "</plan>",
                "The feed edge is `message`, `story`, and `attachments`. Nothing in that reference is a layout hint, so the jump is ours. The chip should reserve its row before `measureStory()` runs.",
            ].join("\n"),
            timestamp: next(45),
            model: "auto",
            stats: {
                timeMs: 11000,
                tokens: 3900,
                inputTokens: 2600,
                outputTokens: 1300,
                usedAuto: true,
                reasoningEffort: "low",
                mode: "Agent",
            },
        },
        {
            role: "user",
            content: "Quiet chip, and keep the see-why delay under 100ms. Show me the options before you write it.",
            timestamp: next(20),
        },
        {
            role: "assistant",
            content: [
                "<think>",
                "They want a quiet chip and a delay cap. Show the three weights we already use on integrity surfaces, then inspect the local story.",
                "</think>",
                `<questions id="ask-chip" status="answered">`,
                JSON.stringify({
                    questions: [
                        {
                            id: "weight",
                            prompt: "Which See why weight should land on home?",
                            options: [
                                { id: "quiet", label: "Quiet", recommended: true },
                                { id: "solid", label: "Solid" },
                                { id: "tint", label: "Tint" },
                            ],
                        },
                    ],
                    answers: { weight: "quiet" },
                }),
                `</questions>`,
                `<generated_svg prompt="Small integrity mark for the See why chip" credits="0.20">${CHIP_MARK}</generated_svg>`,
                `<generated_image prompt="Home feed story with a quiet See why row reserved" credits="0.40">${STORY_SHOT}</generated_image>`,
                `<sent_file name="feed-story.jpg" type="image/svg+xml" title="Home story">${STORY_SHOT}</sent_file>`,
                "<inspect_runtime url=\"https://www.facebook.com/\" kind=\"Chromium\">",
                "Console · 1 warning · story shift 18px after WarningLabel · no page error",
                "</inspect_runtime>",
                "Quiet is the one that matches the rest of home. The mark is only if we need it in the chip chrome later. Local inspect still shows the 18px shift, which is the late commit, not the weight.",
            ].join("\n"),
            timestamp: next(35),
            model: "auto",
            stats: {
                timeMs: 16000,
                tokens: 6400,
                inputTokens: 4100,
                outputTokens: 2300,
                usedAuto: true,
                reasoningEffort: "medium",
                mode: "Visual",
            },
        },
        {
            role: "user",
            content: "Land Quiet. Ping #feed-integrity when the unit test is green. If the task create bounces, leave it for me to approve.",
            timestamp: next(18),
        },
        {
            role: "assistant",
            content: [
                "<status>Reserving the chip row</status>",
                "<search>reserveChip measureStory</search>",
                "<search_result>www/js/feed/integrity/layout/reserveChip.js</search_result>",
                "<grep>measureStory\\(</grep>",
                "<ls>www/js/feed/integrity</ls>",
                "<rename_chat>Feed warning jump</rename_chat>",
                "<mkdir>www/js/feed/integrity/layout</mkdir>",
                "<create_file>www/js/feed/integrity/layout/reserveChip.js</create_file>",
                "<edit file=\"www/js/feed/integrity/layout/reserveChip.js\">",
                "<original>",
                "",
                "</original>",
                "<replacement>",
                "export function reserveChip(theater) {",
                "  return theater ? 0 : 28;",
                "}",
                "</replacement>",
                "</edit>",
                "<edit file=\"www/js/feed/integrity/WarningLabel.react.js\">",
                `<original>`,
                LABEL_BEFORE,
                `</original>`,
                `<replacement>`,
                LABEL_AFTER,
                `</replacement>`,
                "</edit>",
                "<edit_pending id=\"demo-edit-delay\" file=\"www/js/feed/integrity/seeWhyDelay.js\" status=\"applied\">",
                "<original>",
                "export const SEE_WHY_DELAY_MS = 180;",
                "</original>",
                "<replacement>",
                "export const SEE_WHY_DELAY_MS = 80;",
                "</replacement>",
                "</edit_pending>",
                "<edit_pending id=\"demo-edit-copy\" file=\"www/js/feed/integrity/copy.js\" status=\"rejected\">",
                "<original>",
                "Why am I seeing this?",
                "</original>",
                "<replacement>",
                "See why",
                "</replacement>",
                "</edit_pending>",
                "<edit_pending id=\"demo-edit-test\" file=\"www/js/feed/integrity/WarningLabel-test.js\" status=\"pending\">",
                "<original>",
                "test(\"chip does not move the story\", () => {});",
                "</original>",
                "<replacement>",
                "test(\"chip does not move the story\", () => {",
                "  expect(shift).toBe(0);",
                "});",
                "</replacement>",
                "</edit_pending>",
                "<run>js1 www/js/feed/integrity/WarningLabel-test.js</run>",
                "<terminal_command id=\"demo-term-unit\" status=\"completed\" exit=\"0\">",
                "js1 www/js/feed/integrity/WarningLabel-test.js",
                "",
                "✓ reserved row is 28px on home",
                "✓ theater layout reserves nothing",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-lint\" status=\"error\" exit=\"1\">",
                "arc lint www/js/feed/integrity",
                "",
                "✗ seeWhyDelay.js: unused import RankingHoldout",
                "</terminal_command>",
                "<terminal_command id=\"demo-term-lint-2\" status=\"completed\" exit=\"0\">",
                "arc lint www/js/feed/integrity",
                "",
                "✓ clean",
                "</terminal_command>",
                "<tool_result>",
                "[read_lints]",
                "www/js/feed/integrity/WarningLabel.react.js: clean",
                "</tool_result>",
                "<terminal_command id=\"demo-term-dev\" status=\"background\" session=\"2\">",
                "www watch feed/integrity",
                "",
                "watching www/js/feed/integrity",
                "</terminal_command>",
                "<tool_result>",
                "[list_terminals]",
                "2  background  www watch feed/integrity",
                "</tool_result>",
                "<tool_result>",
                "[terminal_read]",
                "rebuilt WarningLabel.react.js",
                "</tool_result>",
                "<terminal_command id=\"demo-term-e2e\" status=\"pending\">",
                "buck test www/js/feed/integrity:story_shift",
                "",
                "Awaiting approval: hits the home feed fixture",
                "</terminal_command>",
                "<git_operation op=\"diff\">",
                "[file] www/js/feed/integrity/WarningLabel.react.js",
                "@@ WarningLabel",
                "-  return <Chip label=\"See why\" reason={props.reason} />;",
                "+      reserveHeight",
                "</git_operation>",
                "<git_operation op=\"stage\">",
                "Staged www/js/feed/integrity/WarningLabel.react.js",
                "</git_operation>",
                "<git_operation op=\"status\">",
                "M www/js/feed/integrity/WarningLabel.react.js",
                "A www/js/feed/integrity/layout/reserveChip.js",
                "</git_operation>",
                "<git_operation op=\"log\">",
                "c91a feed: reserve warning chip on home",
                "18ff feed: see-why copy",
                "</git_operation>",
                "<plugin_call toolkit=\"slack\" slug=\"SLACK_SEND_MESSAGE\" label=\"Send message\" status=\"ok\">",
                JSON.stringify({
                    title: "Quiet chip reserves its row",
                    channel: "#feed-integrity",
                    from: "Shape",
                    sent: "Just now",
                }),
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_LIST_ISSUES\" label=\"List issues\" status=\"ok\">",
                JSON.stringify({
                    title: "Feed integrity",
                    team: "Feed",
                    attention: 2,
                    issues: [
                        { title: "FEED-18441", state: "Open", note: "Story shift fixture" },
                        { title: "FEED-18402", state: "Done", note: "See why copy" },
                        { title: "FEED-18390", state: "Open", note: "Theater must not reserve" },
                    ],
                }),
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"rejected\">",
                JSON.stringify({
                    title: "Story shift fixture",
                    project: "Integrity",
                    reason: "Project required",
                }),
                "</plugin_call>",
                "<plugin_call toolkit=\"linear\" slug=\"LINEAR_CREATE_ISSUE\" label=\"Create issue\" status=\"pending\" id=\"demo-plugin-task\">",
                JSON.stringify({
                    title: "Leftover story-shift fixture",
                    team: "Feed Integrity",
                    priority: "High",
                }),
                "</plugin_call>",
                "<plugin_call toolkit=\"github\" slug=\"GITHUB_CREATE_PR_COMMENT\" label=\"Comment on PR\" status=\"ok\">",
                JSON.stringify({
                    title: "Reserve the See why row",
                    repo: "facebook/facebook",
                    pull: "#18441",
                    state: "Open",
                }),
                "</plugin_call>",
                "<subagent id=\"demo-sub-layout\" agent=\"Feed layout\" model=\"auto\" status=\"done\">",
                "Reserved 28px on home and 0 in theater. measureStory() now sees the chip row.",
                "</subagent>",
                "<subagent_ref id=\"demo-sub-layout\" agent=\"Feed layout\" model=\"auto\" task=\"Reserve the See why row before measureStory\" status=\"done\" />",
                "Quiet chip is in, and the see-why delay is 80ms. I left the copy change alone after you would have rejected “Why am I seeing this?”. The unit test failed once on an unused ranking import, then passed. The story-shift buck test is waiting on you.",
            ].join("\n"),
            timestamp: next(90),
            model: "auto",
            stats: {
                timeMs: 42000,
                tokens: 15200,
                inputTokens: 9800,
                outputTokens: 5400,
                usedAuto: true,
                reasoningEffort: "high",
                mode: "Code",
            },
        },
        {
            role: "user",
            content: "Write the review. The policy diff looked cut off in the preview. Drop the old overlay helper if nothing calls it.",
            timestamp: next(22),
        },
        {
            role: "assistant",
            content: [
                "<thought>",
                "They want a review they can skim, the full label diff, and the unused overlay file gone.",
                "</thought>",
                "<status>Reviewing the chip</status>",
                "<chart>{\"title\":\"Story shift\",\"points\":[{\"label\":\"Before\",\"value\":18},{\"label\":\"After\",\"value\":0}]}</chart>",
                "<insight_card>Reserved row is 28px on home and 0 in theater.</insight_card>",
                "<git_operation op=\"diff\" status=\"completed\">www/js/feed/integrity/WarningLabel.react.js</git_operation>",
                "<git_operation op=\"branches\" status=\"completed\">* fix/see-why\n  main</git_operation>",
                "<status>Waiting for a response</status>",
                "<cat start=\"1\" end=\"40\">www/js/feed/integrity/WarningLabel.react.js</cat>",
                "<edit file=\"www/js/feed/integrity/WarningLabel.react.js\">",
                `<original>`,
                LABEL_BEFORE,
                `</original>`,
                `<replacement>`,
                LABEL_AFTER,
                `</replacement>`,
                "</edit>",
                "<delete_file>www/js/feed/integrity/OverlayWarning.js</delete_file>",
                "<rename_file>www/js/feed/integrity/legacyDelay.js → www/js/feed/integrity/seeWhyDelay.js</rename_file>",
                "<review_debate model=\"auto\">",
                JSON.stringify({
                    verdict: {
                        confirmed_issues: [
                            "measureStory() ran before WarningLabel committed, so the body dropped 18px.",
                            "Theater layout must not reserve a chip row.",
                        ],
                        disputed_points: [
                            "See-why copy stays “See why”. The longer string was rejected.",
                        ],
                        confidence: "high",
                        minimal_fix_plan: [
                            "Reserve the row before measure.",
                            "Cap the delay at 80ms.",
                        ],
                        tipping_evidence: [
                            "WarningLabel-test: reserved row is 28px on home.",
                            "Oncall log: shift=18px on surface=home.",
                        ],
                    },
                }),
                "</review_debate>",
                "<plan_saved path=\".shape/plans/feed-warning-jump.md\" title=\"Feed warning jump\">",
                "# Feed warning jump",
                "",
                "## Goal",
                "Reserve the chip row before measureStory() so the story does not shift.",
                "",
                "## Todos",
                "- [ ] Find the late measure",
                "- [ ] Land the quiet chip",
                "- [ ] Approve the story-shift test",
                "</plan_saved>",
                "<git_operation op=\"commit\">",
                "feed: reserve See why before story measure",
                "</git_operation>",
                "<todos title=\"Feed warning jump\">",
                "<todo id=\"1\" status=\"done\">Find the late measure</todo>",
                "<todo id=\"2\" status=\"done\">Land the quiet chip</todo>",
                "<todo id=\"3\" status=\"pending\">Approve the story-shift test</todo>",
                "<todo id=\"4\" status=\"cancelled\">Ranking holdout</todo>",
                "</todos>",
                "",
                "# Feed warning jump",
                "",
                "Home stories were dropping **18px** after paint because `measureStory()` ran before the chip existed. Theater is unchanged.",
                "",
                "## What landed",
                "",
                "1. `WarningLabel` reserves its row.",
                "2. See-why delay is *80ms*.",
                "3. ~~OverlayWarning.js~~ is gone.",
                "",
                "- Ranking experiment: left alone",
                "- Copy change: rejected",
                "",
                "| File | Change |",
                "| --- | --- |",
                "| `WarningLabel.react.js` | reserveHeight |",
                "| `seeWhyDelay.js` | 180ms to 80ms |",
                "| `OverlayWarning.js` | deleted |",
                "",
                "> The public feed fields are still message, story, and attachments.",
                "",
                "---",
                "",
                "```js",
                "const row = theater ? 0 : 28;",
                "measureStory({ reserved: row });",
                "```",
                "",
                "Follow-up is [FEED-18441](https://github.com/facebook/facebook/pull/18441) after the buck test is approved.",
                "",
                "- [x] Unit test",
                "- [ ] Story-shift fixture",
                "",
                "Full file is `www/js/feed/integrity/WarningLabel.react.js`. The diff above is the whole function, not a clip.",
            ].join("\n"),
            timestamp: next(55),
            model: "auto",
            stats: {
                timeMs: 20000,
                tokens: 8800,
                inputTokens: 5400,
                outputTokens: 3400,
                usedAuto: true,
                reasoningEffort: "medium",
                mode: "Review",
            },
        },
    ];
}
