"use client";

import type { ComponentType } from "react";
import type { IconProps } from "@primer/octicons-react";
import {
    AgentIcon,
    AlertFillIcon,
    AlertIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowSwitchIcon,
    ArrowUpIcon,
    BellFillIcon,
    BellIcon,
    BlockedIcon,
    BoldIcon,
    BookIcon,
    BugIcon,
    CheckCircleFillIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleIcon,
    CloudIcon,
    CloudOfflineIcon,
    CodeIcon,
    ColumnsIcon,
    CommandPaletteIcon,
    CommentDiscussionIcon,
    CopyIcon,
    CrosshairsIcon,
    DashIcon,
    DependabotIcon,
    DeviceDesktopIcon,
    DownloadIcon,
    EyeClosedIcon,
    EyeIcon,
    FileDirectoryFillIcon,
    FileDirectoryIcon,
    FileIcon,
    FilterIcon,
    FoldIcon,
    GearIcon,
    GitBranchIcon,
    GitCommitIcon,
    GitMergeIcon,
    GlobeIcon,
    GrabberIcon,
    HistoryIcon,
    HomeIcon,
    HorizontalRuleIcon,
    HubotIcon,
    ImageIcon,
    InfoIcon,
    ItalicIcon,
    KebabHorizontalIcon,
    KeyIcon,
    LinkExternalIcon,
    LinkIcon,
    ListOrderedIcon,
    ListUnorderedIcon,
    LockIcon,
    MarkGithubIcon,
    MaximizeIcon,
    MinimizeIcon,
    MoonIcon,
    NoteIcon,
    PaintbrushIcon,
    PaperAirplaneIcon,
    PaperclipIcon,
    PasteIcon,
    PencilIcon,
    PersonIcon,
    PinIcon,
    PinSlashIcon,
    PlayIcon,
    PlusIcon,
    PulseIcon,
    QuestionIcon,
    RedoIcon,
    RocketIcon,
    RowsIcon,
    SearchIcon,
    ShieldIcon,
    SidebarCollapseIcon,
    SidebarExpandIcon,
    SparkleFillIcon,
    SparkleIcon,
    SquareFillIcon,
    SquareIcon,
    StarFillIcon,
    StarIcon,
    StopIcon,
    StrikethroughIcon,
    SunIcon,
    SyncIcon,
    TagIcon,
    TasklistIcon,
    TerminalIcon,
    ThreeBarsIcon,
    TrashIcon,
    UndoIcon,
    UnlockIcon,
    UploadIcon,
    WrapIcon,
    XIcon,
    ZapIcon,
    XCircleFillIcon,
    XCircleIcon,
} from "@primer/octicons-react";
import { cn } from "@/lib/utils";

type OcticonComponent = ComponentType<IconProps>;

/**
 * Product UI icons: GitHub Octicons.
 * File/folder icons stay on the VS Code set in lib/ui/icons/files.ts.
 */
const ICONS: Record<string, OcticonComponent> = {
    close: XIcon,
    clear: XIcon,
    cancel: XIcon,
    add: PlusIcon,
    remove: DashIcon,
    error: XCircleIcon,
    x_circle: XCircleIcon,
    warning: AlertFillIcon,
    info: InfoIcon,
    check: CheckIcon,
    check_circle: CheckCircleIcon,
    check_box: CheckIcon,
    check_box_outline_blank: SquareIcon,
    radio_button_unchecked: CircleIcon,
    circle: CircleIcon,
    search: SearchIcon,
    brain: SparkleIcon,
    my_location: CrosshairsIcon,
    refresh: SyncIcon,
    sync: SyncIcon,
    more_horiz: KebabHorizontalIcon,
    more_vert: GrabberIcon,
    description: NoteIcon,
    note_add: FileIcon,
    format_align_left: ListUnorderedIcon,
    file_copy: CopyIcon,
    content_copy: PasteIcon,
    list: ListUnorderedIcon,
    format_list_bulleted: ListUnorderedIcon,
    list_alt: TasklistIcon,
    checklist: TasklistIcon,
    expand_more: ChevronDownIcon,
    expand_less: ChevronUpIcon,
    keyboard_arrow_down: ChevronDownIcon,
    keyboard_arrow_right: ChevronRightIcon,
    keyboard_arrow_left: ChevronLeftIcon,
    keyboard_arrow_up: ChevronUpIcon,
    chevron_right: ChevronRightIcon,
    chevron_left: ChevronLeftIcon,
    terminal: TerminalIcon,
    delete: TrashIcon,
    light_mode: SunIcon,
    dark_mode: MoonIcon,
    open_in_new: LinkExternalIcon,
    merge: GitMergeIcon,
    commit: GitCommitIcon,
    cloud_download: CloudOfflineIcon,
    cloud_upload: UploadIcon,
    download: DownloadIcon,
    upload: UploadIcon,
    account_tree: GitBranchIcon,
    tag: TagIcon,
    sell: TagIcon,
    bookmark: TagIcon,
    code: CodeIcon,
    insert_drive_file: FileIcon,
    chat: CommentDiscussionIcon,
    forum: CommentDiscussionIcon,
    play_arrow: PlayIcon,
    play: PlayIcon,
    stop: StopIcon,
    bug_report: BugIcon,
    folder: FileDirectoryIcon,
    folder_open: FileDirectoryFillIcon,
    settings: GearIcon,
    menu: ThreeBarsIcon,
    three_bars: ThreeBarsIcon,
    edit: PencilIcon,
    save: DownloadIcon,
    home: HomeIcon,
    undo: UndoIcon,
    redo: RedoIcon,
    tune: GearIcon,
    arrow_back: ArrowLeftIcon,
    arrow_forward: ArrowRightIcon,
    arrow_upward: ArrowUpIcon,
    arrow_downward: ArrowDownIcon,
    pause: StopIcon,
    replay: SyncIcon,
    fast_forward: ChevronRightIcon,
    double_arrow: ChevronRightIcon,
    remove_circle_outline: BlockedIcon,
    star: StarIcon,
    star_border: StarIcon,
    lock: LockIcon,
    lock_open: UnlockIcon,
    history: HistoryIcon,
    send: PaperAirplaneIcon,
    "send-ins": PaperAirplaneIcon,
    attachment: PaperclipIcon,
    image: ImageIcon,
    public: GlobeIcon,
    language: GlobeIcon,
    visibility: EyeIcon,
    visibility_off: EyeClosedIcon,
    palette: PaintbrushIcon,
    brush: PaintbrushIcon,
    format_color_fill: PaintbrushIcon,
    color_lens: PaintbrushIcon,
    colorize: CrosshairsIcon,
    auto_awesome: SparkleIcon,
    desktop_windows: DeviceDesktopIcon,
    monitor: DeviceDesktopIcon,
    security: ShieldIcon,
    block: BlockedIcon,
    unfold_more: ChevronDownIcon,
    push_pin: PinIcon,
    keep_off: PinSlashIcon,
    notifications: BellIcon,
    notification: BellIcon,
    vertical_split: ColumnsIcon,
    split_horizontal: RowsIcon,
    create_new_folder: FileDirectoryIcon,
    unfold_less: MinimizeIcon,
    crop_square: SquareIcon,
    grid_view: ColumnsIcon,
    rotate_left: UndoIcon,
    rotate_right: RedoIcon,
    swap_horiz: ArrowSwitchIcon,
    swap_vert: ArrowSwitchIcon,
    width: HorizontalRuleIcon,
    height: HorizontalRuleIcon,
    format_bold: BoldIcon,
    format_italic: ItalicIcon,
    format_strikethrough: StrikethroughIcon,
    format_underlined: ItalicIcon,
    format_list_numbered: ListOrderedIcon,
    person: PersonIcon,
    rocket_launch: RocketIcon,
    keyboard: CommandPaletteIcon,
    link: LinkIcon,
    link_off: LinkIcon,
    view_stream: RowsIcon,
    wrap_text: WrapIcon,
    find_replace: SearchIcon,
    command: CommandPaletteIcon,
    rocket: RocketIcon,
    user: PersonIcon,
    bot: HubotIcon,
    maximize: MaximizeIcon,
    minimize: MinimizeIcon,
    project: HomeIcon,
    structure: ListUnorderedIcon,
    outline: ListOrderedIcon,
    git: GitBranchIcon,
    github: MarkGithubIcon,
    agents: AgentIcon,
    connected: PulseIcon,
    disconnected: LinkIcon,
    cloud: CloudIcon,
    help: QuestionIcon,
    filter: FilterIcon,
    changes: GitCommitIcon,
    puzzle: BookIcon,
    caret_down: ChevronDownIcon,
    caret_right: ChevronRightIcon,
    sidebar_collapse: SidebarCollapseIcon,
    sidebar_expand: SidebarExpandIcon,
    fold: FoldIcon,
    view_compact: SidebarCollapseIcon,
    zap: ZapIcon,
    dependabot: DependabotIcon,
};

const FILLED_ICONS: Partial<Record<string, OcticonComponent>> = {
    warning: AlertFillIcon,
    check_circle: CheckCircleFillIcon,
    error: XCircleFillIcon,
    x_circle: XCircleFillIcon,
    star: StarFillIcon,
    notifications: BellFillIcon,
    notification: BellFillIcon,
    brain: SparkleFillIcon,
    auto_awesome: SparkleFillIcon,
    crop_square: SquareFillIcon,
};

export function Icon({
    name,
    className,
    size = 16,
    filled = false,
}: {
    name: string;
    className?: string;
    size?: number | string;
    filled?: boolean;
}) {
    const safeName = name ?? "";
    const key = ICONS[safeName] ? safeName : safeName.replace(/_/g, "-");
    const IconComponent =
        (filled && FILLED_ICONS[key]) ||
        ICONS[key] ||
        ICONS[safeName] ||
        SquareIcon;
    const numericSize = typeof size === "string" ? Number.parseInt(size, 10) || 16 : size;

    return (
        <IconComponent
            size={numericSize}
            verticalAlign="middle"
            className={cn("shrink-0", className)}
            aria-hidden
        />
    );
}
